# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('day_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('map', models.IntegerField(verbose_name='Карта')),
                ('row', models.IntegerField(verbose_name='Ряд')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('cemetery', models.CharField(max_length=200, verbose_name='Кладбище')),
            ],
            options={
                'verbose_name': 'Могила',
                'verbose_name_plural': 'Могилы',
            },
        ),
    ]
