# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.RenameField(
            model_name='graves',
            old_name='map',
            new_name='sector',
        ),
        migrations.AddField(
            model_name='graves',
            name='big_photo',
            field=models.FileField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graves',
            name='part_ww',
            field=models.IntegerField(default=1, verbose_name='Учавствовал ли во ВоВ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graves',
            name='photo',
            field=models.FileField(default=1, upload_to='', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graves',
            name='birthday',
            field=models.CharField(default=datetime.datetime(2016, 10, 15, 11, 44, 5, 87869, tzinfo=utc), max_length=128, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graves',
            name='cemetery',
            field=models.IntegerField(verbose_name='Церковь'),
        ),
        migrations.AlterField(
            model_name='graves',
            name='day_of_death',
            field=models.CharField(default=datetime.datetime(2016, 10, 15, 11, 44, 14, 44381, tzinfo=utc), max_length=128, verbose_name='Дата смерти'),
            preserve_default=False,
        ),
    ]
