# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0002_auto_20161015_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('text', django_summernote.fields.SummernoteTextField(verbose_name='Содержимое')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.AlterField(
            model_name='graves',
            name='number',
            field=models.CharField(max_length=200, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='graves',
            name='row',
            field=models.CharField(max_length=200, verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='graves',
            name='sector',
            field=models.CharField(max_length=200, verbose_name='Карта'),
        ),
    ]
