# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0003_auto_20161205_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Закоголовок')),
                ('before_photo', models.ImageField(upload_to='', verbose_name='Фото До')),
                ('after_photo', models.ImageField(upload_to='', verbose_name='Фото После')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Наш проект',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
    ]
