# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0004_ourprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('translation', models.TextField(verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Памятник',
                'verbose_name_plural': 'Памятники',
            },
        ),
        migrations.AlterField(
            model_name='graves',
            name='cemetery',
            field=models.IntegerField(choices=[(1, 'Текстиль'), (2, 'Чигатай')], verbose_name='Кладбище'),
        ),
    ]
