# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0005_auto_20170306_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorials',
            name='name',
        ),
        migrations.AddField(
            model_name='memorials',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер могилы'),
            preserve_default=False,
        ),
    ]
