# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-06 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graves', '0007_auto_20170306_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorials',
            name='photo',
            field=models.CharField(max_length=100, verbose_name='Фото'),
        ),
    ]
