# Generated by Django 4.2.18 on 2025-01-28 11:37

from django.db import migrations


def populate_new_field(apps, schema_editor):
    Graves = apps.get_model('graves', 'Graves')
    for obj in Graves.objects.all():
        name = obj.name.split(' ')
        if name:
            obj.last_name = name[0]

        if len(name) > 1:
            obj.first_name = name[1]

        if len(name) > 2:
            obj.third_name = name[2]

        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('graves', '0010_graves_first_name_graves_last_name_graves_third_name'),
    ]

    operations = [
        migrations.RunPython(populate_new_field),
    ]
